### ISSUE TITLE
Patch requests

### ISSUE THREAD

**Issue by Barbarossa93** [bakkeby/tabbed-flexipatch#1]
Hello again,

There's a few patches for tabbed that I'd love to see implemented if you're willing to include them. They are:
- [x] [xresources](https://tools.suckless.org/tabbed/patches/xresources/)
- [x] [xft](https://tools.suckless.org/tabbed/patches/xft/)
- [x] [bar-height](https://tools.suckless.org/tabbed/patches/bar-height/)

Thank you for these flexpatch setups! Don't think I've ran into anything as incredible lately

**Comment by bakkeby** [comment]
I didn't take the bar-height patch as-is, made a small amendment to allow the height of the bar to be derived by the font size (as per default) by leaving the `barheight` variable as 0.

**Comment by bakkeby** [comment]
It looks like the xft patch was merged upstream so that's already there.

**Comment by Barbarossa93** [comment]
Perfect, everything (I've tried/enabled) works as expected. Thank you so much @bakkeby ! Seriously, do you have a way I could donate to you? I greatly appreciate all of your work on your flexipatch projects!

**Comment by bakkeby** [comment]
You really don't need to worry about donations, just enjoy it :)

That said if you do feel strongly about it I have a sponsor button on the [dwm-flexipatch](https://github.com/bakkeby/dwm-flexipatch/) project but also there you may want to consider helping out suckless.org with server costs etc. instead.
